language: node_js
node_js:
  - "0.10"

before_script:
  - sudo apt-get update
  - sudo apt-get install chromium-browser
  - sudo apt-get install firefox
  - export DISPLAY=:99.0
  - export CHROME_BIN=chromium-browser
  - sh -e /etc/init.d/xvfb start
  - npm install > /dev/null
  - node_modules/.bin/gulp build
  - node_modules/.bin/gulp build:release
  - node_modules/.bin/gulp run:server &
  - sleep 5

script:
  - node_modules/.bin/gulp run:test:unit
  - node_modules/.bin/gulp run:test:e2e
