language: node_js
node_js:
  - "0.10"
  - "0.12"

before_script:
  - export DISPLAY=:99.0
  - sudo chmod 1777 /dev/shm
  - Xvfb :99.0 -extension RANDR > /dev/null &
  - npm test > /dev/null
  - node_modules/.bin/gulp build:release
  - node_modules/.bin/gulp run:server &
  - sleep 5

script:
  - node_modules/.bin/gulp run:test:e2e

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/32efdc70f5ad67ec2ad8
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
